apiVersion: v1
kind: PersistentVolume
metadata:
  name: druid-volume-pv
  labels:
    type: local
spec:
  storageClassName: druid-volume
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/druid"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: druid-volume-pvc
spec:
  storageClassName: druid-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---