apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-pa
  namespace: kafka
spec:
  kafka:
    # broker version
    version: 3.2.0
    # initial replicas
    replicas: 1
    # provision lbs
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: server
        port: 9094
        type: nodeport
        tls: false
        configuration:
          brokers:
            - broker: 0
              advertisedHost: localhost
    config:
        default.replication.factor: 1
        num.partitions: 9
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
        log.message.format.version: "3.2"
        inter.broker.protocol.version: "3.2"
        log.retention.hours: 24
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}